// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8J3r7kbLDMen4_TqyDa-nMoSSEVzrad0',
    appId: '1:365130743379:web:837b268270e529608e50a6',
    messagingSenderId: '365130743379',
    projectId: 'uas-made',
    authDomain: 'uas-made.firebaseapp.com',
    storageBucket: 'uas-made.appspot.com',
    measurementId: 'G-X4QTEFR3MJ',
    databaseURL: 'https://uas-made-default-rtdb.asia-southeast1.firebasedatabase.app',

  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM2_y8Mb8oo7i7wHlE12V1SpHYNeUo5ls',
    appId: '1:365130743379:android:1a8556ba730bc54a8e50a6',
    messagingSenderId: '365130743379',
    projectId: 'uas-made',
    storageBucket: 'uas-made.appspot.com',
     databaseURL: 'https://uas-made-default-rtdb.asia-southeast1.firebasedatabase.app',

  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8NChN5SSmtl1gJvrHe-PlIzabKzDHZRo',
    appId: '1:365130743379:ios:a2635d9566ecc0c98e50a6',
    messagingSenderId: '365130743379',
    projectId: 'uas-made',
    storageBucket: 'uas-made.appspot.com',
    iosClientId: '365130743379-vp31s5bjdnj47gt1f93jvq9h7i46nf90.apps.googleusercontent.com',
    iosBundleId: 'com.example.uasMade',
     databaseURL: 'https://uas-made-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8NChN5SSmtl1gJvrHe-PlIzabKzDHZRo',
    appId: '1:365130743379:ios:9946d491aac656fb8e50a6',
    messagingSenderId: '365130743379',
    projectId: 'uas-made',
    storageBucket: 'uas-made.appspot.com',
    iosClientId: '365130743379-7dfoni642b1qobgjoc47n27feqh2j16r.apps.googleusercontent.com',
    iosBundleId: 'com.example.uasMade.RunnerTests',
     databaseURL: 'https://uas-made-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
}
